name: Update README

on:
  push:
    branches:
      - main
      - AI-update

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Find PNG files
        id: find-files
        run: |
            png_files=$(find AI_generated -name '*.png')
            echo "files=$png_files" >> $GITHUB_ENV

      - name: Update README
        run: |
            echo "## Artwork" > AI_generated/README.md
            echo "" >> AI_generated/README.md
            echo "The following PNG files are available:" >> AI_generated/README.md
            echo "" >> AI_generated/README.md
            echo "\`\`\`" >> AI_generated/README.md
            cat $GITHUB_ENV | grep files= | cut -d '=' -f2- >> AI_generated/README.md
            echo "\`\`\`" >> AI_generated/README.md

      - name: Commit and push changes
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add AI_generated/README.md
            git commit -m "Update README with PNG files in AI_generated folder"
            git push